
baseURL: http://ladybuginthemug.github.io/
languageCode: en-us
title: pushingbuttons 
theme: PaperMod
defaultTheme: auto

params:
    profileMode:
        enabled: true
        subtitle: "Hi there"
        ShowBreadCrumbs: true
    menu:
      main:
        - name: "x"
              url: "/"
        - name: "writings"
              url: "/docs/"
   



    ShowCodeCopyButtons: true
    ShowToc: true
    ShowReadingTime: true
  
