
baseURL: http://ladybuginthemug.github.io/
languageCode: en-us
title: pushingbuttons 
theme: PaperMod
defaultTheme: dark
disableThemeToggle: true

# intro
params:
  homeInfoParams:
    Content: >
        defence & automation

# navigation settigs
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
  socialIcons:
    - name: Github
      url: "https://github.com/ladybuginthemug"



# Additional Site Settings (add more settings if necessary)
params:
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    hideSummary: true
    

# mark up settings 
markup:
  highlight:
    #anchorLineNos: true
    guessSyntax: true
    #lineNos: true
    noClasses: true
    style: native
    
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true  
