
baseURL: http://ladybuginthemug.github.io/
languageCode: en-us
title: pushingbuttons 
theme: PaperMod
defaultTheme: auto

params:
    homeInfoParams:
        Title: Hi there wave

params:
    ShowCodeCopyButtons: true
    ShowToc: true
    ShowReadingTime: true
  
