
baseURL: http://ladybuginthemug.github.io/
languageCode: en-us
title: pushingbuttons 
theme: hello-friend





languages:
  en:
    title: Your site title
    keywords: ''
    menuMore: Show more
    writtenBy: by
    readMore: Read 
    readOtherPosts: read other posts
    newerPosts: newer posts
    olderPosts: older posts
    dateFormatSingle:  02-Jan-2006
    dateFormatList: 02-Jan-2006
    ShowReadingTime: true
    MinuteReadingTime: min read

    params:
      logo:
        logoText: pushingbuttons
        logoHomeLink: /
    
# navigation settigs
menu:
  main:
    - identifier: blog
      name: writings
      url: /writings/
      weight: 1
    - identifier: projects
      name: projects
      url: /projects/
      weight: 2
    - identifier: categories
      name: categories
      url: /categories/
      weight: 3
    - identifier: git
      name: git
      rel: external
      pre: <i class="fa fa-heart"></i>
      url: https://github.com/ladybuginthemug
      weight: 30



