name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download Hugo binary
        run: |
          HUGO_VERSION=0.148.1
          curl -L -o /tmp/hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz"
          echo "69f787720e7bad18f13dce9d7c494f4a908bfdffbfdea483e6df529268aeec37  /tmp/hugo.tar.gz" | sha256sum -c -
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo
          mv ${RUNNER_TEMP}/hugo /usr/local/bin/hugo

      - name: Build Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: ladybuginthemug
          user_email: 41898282+ladybuginthemug@users.noreply.github.com


